apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pranoj85-dev
  name: myopenshiftdemo-deployment
  annotations: {}
spec:
  selector:
    matchLabels:
      app: myopenshiftdemo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: myopenshiftdemo-deployment
    spec:
      containers:
        - name: myopenshiftdemo
          image: 'pranoj85/myopenshiftdemo:v1'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: appColor
              valueFrom :
                configMapKeyRef :
                  name : app-config
                  key : appColor
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
